import { CategoriaProducto, Producto } from "../domain/models";

const CATEGORIAS_SEED = [
  "DULCERIA",
  "COMESTIBLES",
  "AGUARDIENTE",
  "CHAMPAÑA",
  "CERVEZA",
  "CIGARRILLO",
  "VODKA",
  "GINEBRA",
  "BEBIDAS FRIAS",
  "VARIOS",
  "WHISKY",
  "VINO",
  "RON",
  "COCTELES",
  "GASEOSAS",
] as const;

const PRODUCTOS_POR_CATEGORIA: Record<string, string[]> = {
  DULCERIA: ["Bom Bom Bun", "Halls", "Trident x18", "Trident x5"],
  COMESTIBLES: [
    "Aceituna alfresco 125g",
    "Aceituna alfresco 250g",
    "Cerezas elfortin 125g",
    "Cerezas elfortin 250g",
    "Chicharron americano natural x100g",
    "Chicharron Monterrojo",
    "Choclitos x230gg",
    "De todido bbq x165g",
    "De todido bbq x65g",
    "De todido limon x165g",
    "De todido mix x165g",
    "De todido mix x65",
    "De todido natural x65g",
    "Doritos x185g",
    "Manimoto limon x170g",
    "Manimoto x80g",
    "Margarita pollo x105gr",
    "Margarita Natural",
    "Margarita ondulada Mayonesa",
    "Margarita rc sal marina x120g",
    "Margarita tomate",
    "MONTEROJO",
    "Natuchips platano maduro x135g",
    "Natuchips platano verde x135g",
    "Oreo x12 und",
    "Ritz galleta x12",
  ],
  AGUARDIENTE: [
    "Aguardiente Cumbe",
    "Amarillo 375",
    "Amarillo 1500ml",
    "AMARILLO 1L",
    "Antioqueno azul x1000ml",
    "Amarillo X750ml",
    "Antioqueato verde x1750",
    "Antioqueno Azul X750ml",
    "Antioqueno azul x2000ml",
    "Antioqueno azul x375mi",
    "Antioqueno rojo x 750 ml",
    "Antioqueno real x750ml",
    "Antioqueno rojo x 375ml",
    "Antioqueno verde x375ml",
    "Antioqueno rojo x1L",
    "Antioqueno verde x1L",
    "Antioqueno verde x750ml",
    "Antioqueo Real 24",
    "Cristal x 375ml",
    "Cristal x 750ml",
    "Cristal Xs 1000ml",
    "Cristal Xs 1750ml",
    "Cristal Xs 375ml",
    "Cristal Xs 750ml",
    "litro tetra",
    "Quindiano x375ml",
    "Quindiano x750ml",
    "Tapa roja 24 grados 750ml",
    "Tapa roja 24 grados x375ml",
    "Tapa roja Azu especial 375 ml",
    "Tapa roja special sin azucar x750ml",
    "Tapa roja tradiciona x375ml",
    "Tapa roja tradicional 750ml",
  ],
  "CHAMPAÑA": [
    "CHAMPAGNE GH MUMM",
    "Chandon Delice",
    "Chandon dime sec",
    "Chandon extra brut",
    "Chandon rose",
    "Jp chenet",
    "blanc frizzy lata x250ml",
    "Jp chenet blanco 200ml",
    "Jp chenet blanco 750ml",
    "Jp chenet Divine Muscat",
    "Jp chenet divine x750ml",
    "Jp chenet fashion cassis x200ml",
    "Jp chenet fashion cassis x750ml",
    "Jp chenet rose 200ml",
    "Jp Chenet Rose 750ml",
    "Jp chenet rose frizzy lata 250ml",
    "Jp chenet strawberry x200ml",
    "Jp chenet strawberry x750ml",
    "Moet chandon ice imperial x750ml",
    "Moet chandon rose imperial x750ml",
    "Veuve clicquot brut 750ml",
    "veuve clicquot rose",
  ],
  CERVEZA: [
    "3 cordilleras mestiza x330ml",
    "3 Cordilleras Negra x330ml",
    "3 cordilleras rosada x330ml",
    "3 Cordilleras rose 750",
    "Aguila light lata x330",
    "Andina x473ml",
    "Club colombia dorada lata x330",
    "Corona Extra Bot X330ml",
    "Coronita 210ml",
    "Heineken botella",
    "Poker lata x330",
    "Sol bot x330ml",
    "stella artois",
  ],
  CIGARRILLO: ["Lucky strike", "LYM red x10", "Marlboro fusion x10", "Marlboro gold x10", "Marlboro red x10"],
  VODKA: [
    "Absolut vodka 350ml",
    "Absolut vodka 700 ml",
    "Absolut vodka mandarin x700ml",
    "Absolut vodka raspberri x700ml",
    "Absolut vodka x1000 ml",
    "Jagermeister 1000ml",
    "Jagermeister x350ml",
    "Jagermeister x700ml",
    "SMIRNOF SPICK TAMARINDO",
    "Smirnof vodka red 350",
    "Smirnoff lulo 750ml",
    "Smirnoff lulo x1000ml",
    "Smirnoff lulo x375ml",
    "Smirnoff red vodka x700ml",
    "Vodka finlandia x375ml",
    "Vodka finlandia x750ml",
  ],
  GINEBRA: [
    "Beefeater london 700ml",
    "Beefeater london pink 700ml",
    "Bombay sapphire 500 ml",
    "Bombay sapphire x700ml",
    "Bosque de indias ginebra x700ml",
    "Bull dog london gin 750ml",
    "Falconry Gin",
    "Ginebra monkey 47 x500ml",
    "Gordons london 700ml",
    "Greenals 750 ml",
    "Hendrick 5 cl",
    "Hendricks gin x350ml",
    "Hendricks gin x750ml",
    "Tanqueray gin london 375ml",
    "Tanqueray gin london x700ml",
  ],
  "BEBIDAS FRIAS": [
    "Agua cristal x600ml",
    "Bretana x1500ml",
    "Bretana x300ml",
    "Coca cola lata x330ml",
    "Coctel Viejo De Caldas",
    "Don Simon Sangria 15L",
    "Electrolite",
    "Gatorade",
    "Monster",
    "Red bull energy x250ml",
    "Smirnoff ice GREEN lata 250 ml",
    "Smirnoff ice original lata 250 ml",
  ],
  VARIOS: ["Alka Seltzer", "Bonfiest plus", "Michelada", "Zumo", "Tajim 142"],
  WHISKY: [
    "Baileys 1000ml",
    "Baileys original 375 ml",
    "Baileys original 700 ml",
    "Ballantines 700 ml",
    "Ballantines x 375",
    "Black and white 1000ml",
    "Black and white 375ml",
    "Black and white 700ml",
    "BUCHANANS 18",
    "Buchanans Deluxe 375ml",
    "Buchanans Deluxe X1000ml",
    "Buchanans Deluxe X750ml",
    "Buchanans Master 750ml",
    "Buchanans master x1000ml",
    "BUCHANAS TWO SOUL",
    "Chivas Regal 12yo 700 ml",
    "Chivas regal age 12 years 375ml",
    "Chivas regal age 18 years x700ml",
    "Chivas regal extra 700ml",
    "Clan mcgergor whisky x1000ml",
    "Clan mcgergor whisky x350ml",
    "Clan mcgergor whisky x700ml",
    "Glendfiddich 21 anos 750ml",
    "Glenfiddich 12 anos x750ml",
    "Glenfiddich 12 aos 5cl",
    "Glenfiddich 15 anos x750ml",
    "Glenfiddich 15anos 5cl",
    "Glenfiddich 18 anos x750ml",
    "Glenfiddich x 350",
    "Grants 12 anos triple wood",
    "Grants Whisky x1000ml",
    "Grants whisky x350 ml",
    "Grants whisky x750ml",
    "Highland park 12 years old 700ml",
    "Jack daniel x 200",
    "Jack daniels whisky x375ml",
    "Jack daniels 5cl",
    "jack Daniels Apple",
    "Jack daniels fire whisky x750ml",
    "Jack Daniels Honey Whisky 750ml",
    "Jack daniels honey x375ml",
    "Jack daniels single barrel",
    "Jack daniels whisky x750ml",
    "James Buchanans Red Seal",
    "Jameson whiskey 700 ml",
    "Jhonnie walker 18 years x750ml",
    "Jhonnie walker black label 700ml",
    "Jhonnie walker blue label x750ml",
    "Jhonnie Walker Double Black X750ml",
    "Jhonnie Walker Gold label",
    "Jhonnie walker red label x1000ml",
    "Jhonnie walker red label x375ml",
    "Jhonnie walker red label x700ml",
    "Macallan 12 anos double cash",
    "Macallan 15 anos double cash",
    "Monkey shoulder 5cl",
    "Monkey shoulder x700ml",
    "Old parr 18 anos x750ml",
    "Old parr aged 12 years 500ml",
    "Old parr aged 12 years 750ml",
    "Old Parr Aged 12years 1L",
    "old parr x 200",
    "Passport scotch whisky 1L",
    "Passport scotch whisky 500ml",
    "Passport scotch whisky 750ml",
    "ROYAL SALUTE 21",
    "San marino crema de cafe 700ml",
    "Sir edwards whisky x1000ml",
    "Sir edwards x700ml",
    "Something special 1L",
    "Something special 350ml",
    "Something special 750ml",
    "The famous grouse 700ml",
    "The glenlivet founders reserve 700ml",
    "The glenrothes 12 years old 700ml",
    "The Singleton",
    "William Lawsons whisky 350ml",
    "William Lawsons whisky 750ml",
  ],
  VINO: [
    "Casillero del diablo blanco x375ml",
    "Casillero del diablo cabernet S x375ml",
    "cinzano vermouth extra 750",
    "Cuenca blanco 750ml",
    "dubonnet 375",
    "Finca las moras cabernet suavinon",
    "Gato negro cabernet suavignon 375ml",
    "Gato negro carmenere x750ml",
    "GATO NEGRO MALBEC",
    "Gato negro merlot x750ml",
    "gato negro rose",
    "Gato negro auvignon blanc x 750",
    "Lambruco piccini rosso dolce tinto",
    "Lambrusco giacondi bianco 750 ml",
    "Lambrusco giacondi rose 750 ml",
    "Lambrusco giacondi rosso 750ml",
    "Lambrusco lunato Rosato",
    "Lambrusco lunato Ross0 Dolce",
    "Lambrusco Piccini Blanco D",
    "Lambrusco Piccini Rosado",
    "Lambrusco Riunite",
    "Lambrusco Riunite Rose",
    "Lambrusco Rosso Medici ermete",
    "Manischewizt Cream Peach",
    "Ramon Bilbao Crianza",
    "reservado cabernet",
    "Reservado Suavinong Blanco",
    "Sangria don simon x1000ml",
    "Tarapaca cabernet suavignon",
    "Tarapaca Merlot",
    "Vina Maipo suavvignon blac",
    "Vino casa grajales blanco caja x1000ml",
    "Vino casa grajales tinto caja x1000ml",
    "Vino casillero del diablo blanco x750ml",
    "Vino casillero del diablo cabernet 2018 x750ml",
    "Vino casillero del diablo cabernet 2020 x750ml",
    "Vino casillero del diablo carmenere x750ml",
    "Vino casillero del diablo merlot x750ml",
    "Vino casillero del diablo chardonnay x750ml",
    "Vino casillero del diablo rose x750ml",
    "Vino casillero del diablo malbec x750ml",
    "Vino concha y toro merlot 750 ml",
    "Vino concha y toro rose 750 ml",
    "Vino cuenca merlot 750 ml",
    "Vino dubonnet x750ml",
    "Vino finca escondida cabernet 750ml",
    "Vino finca escondida chardonnay 750ml",
    "Vino finca escondida malbec 750 ml",
    "VINO FINCA LAS MORAS MALBEC",
    "VINO FINCA LAS MORAS MALBEC SELECT",
    "VINO FRONTERA CABERNET S 1500ML",
    "Vino frontera cabernet x750ml",
    "Vino frontera carmenere x750ml",
    "vino frontera chardonnay x750ml",
    "Vino frontera malbec x750ml",
    "Vino frontera merlot x750ml",
    "Vino frontera rose x750ml",
    "Vino frontera suavignon blanco x750ml",
    "Vino gato negro cabernet x750ml",
    "Vino manischewitz cherry x750ml",
    "Vino manischewitz concord grape x750ml",
    "Vino polero cabernet 750ml",
    "Vino polero merlot 750ml",
    "Vino polero suavignon bianco 750ml",
    "Vino vina maipo cabernet x750ml",
    "Vino vina maipo carmenere x750ml",
    "Vino vina maipo chardonnay x750ml",
    "Vino vina maipo merlot x750ml",
    "Vino vina maipo rose x750ml",
  ],
  RON: [
    "Bacardi Mojito x750ml",
    "Crema de ron cheers x700ml",
    "Crema ron medellin 8years",
    "Diplomatico Mantuano",
    "La hechicera 700 ml",
    "Medellin 12 anos x750ml",
    "Medellin 19 anos x750ml",
    "Medellin 3 anos x375ml",
    "Medellin 3 anos x750ml",
    "Medellin 5 anos x375ml",
    "Medellin 5 anos x750ml",
    "Medellin 8 anos 750 ml",
    "Medellin 8 anos x375ml",
    "Medellin dorado x750ml",
    "Medellin extra dos maderos",
    "Parce 12 anos x750ml",
    "Parce 8 anos x750ml",
    "Parce brothers blend x750ml",
    "Ron abuelo",
    "Ron Barcelo anejo",
    "Ron Barcelo Imperial",
    "RON coloma 8 antos",
    "Ron havana club 3 anos x700ml",
    "Ron Pink",
    "Viejo de caldas 15 anos x750ml",
    "VIEJO DE CALDAS 21 ANOS Leon Dormido",
    "Viejo de caldas 5 anos x375ml",
    "Viejo de caldas 5 anos x750ml",
    "Viejo de caldas 8 anos x375ml",
    "Viejo de caldas 8 anos x750ml",
    "Viejo de caldas blanco x750ml",
    "Viejo de caldas Esencial 750",
    "Viejo de caldas Oscuro",
    "Viejo de caldas x1000ml",
    "Viejo de caldas x1750ml",
    "Viejo de caldas x375ml",
    "Viejo De Caldas X750ml",
    "Zacapa 23 anos x700ml",
    "zacapa ambar 12 x750ml",
    "zacapa xo centenario",
  ],
  COCTELES: [],
  GASEOSAS: ["Canada dry x1500ml", "Canada dry x300ml", "del valle citricas", "SCHWWEPPES GINGER 1500 ML"],
};

const BASE_PRECIO_POR_CATEGORIA: Record<string, number> = {
  DULCERIA: 1500,
  COMESTIBLES: 4000,
  AGUARDIENTE: 42000,
  "CHAMPAÑA": 78000,
  CERVEZA: 5000,
  CIGARRILLO: 2800,
  VODKA: 52000,
  GINEBRA: 58000,
  "BEBIDAS FRIAS": 3500,
  VARIOS: 5000,
  WHISKY: 95000,
  VINO: 35000,
  RON: 42000,
  COCTELES: 12000,
  GASEOSAS: 3800,
};

function normalizeNombre(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function calcularPrecio(categoria: string, indice: number): number {
  const base = BASE_PRECIO_POR_CATEGORIA[categoria] ?? 10000;
  return base + (indice % 9) * 1200;
}

export async function runInventorySeed(): Promise<void> {
  let categoriasCreadas = 0;
  let categoriasExistentes = 0;
  let productosCreados = 0;
  let productosExistentes = 0;

  const categoriaIdByNombre = new Map<string, number>();

  for (const categoriaRaw of CATEGORIAS_SEED) {
    const nombre = normalizeNombre(categoriaRaw);
    const existente = await CategoriaProducto.findOne({ where: { nombre } });

    if (existente) {
      categoriasExistentes++;
      categoriaIdByNombre.set(nombre, existente.idCategoria);
      continue;
    }

    const nueva = await CategoriaProducto.create({ nombre } as any);
    categoriasCreadas++;
    categoriaIdByNombre.set(nombre, nueva.idCategoria);
  }

  for (const [categoriaNombreRaw, productos] of Object.entries(PRODUCTOS_POR_CATEGORIA)) {
    const categoriaNombre = normalizeNombre(categoriaNombreRaw);
    const idCategoria = categoriaIdByNombre.get(categoriaNombre);

    if (!idCategoria) {
      console.warn(`[SEED] Categoria no encontrada para productos: ${categoriaNombre}`);
      continue;
    }

    const unicos = Array.from(new Set(productos.map(normalizeNombre).filter(Boolean)));

    for (let i = 0; i < unicos.length; i++) {
      const nombre = unicos[i];
      const existente = await Producto.findOne({ where: { nombre, idCategoria } });

      if (existente) {
        productosExistentes++;
        continue;
      }

      const stockMinimo = 6 + (i % 6);
      const stockActual = stockMinimo + 24 + (i % 8);

      await Producto.create({
        nombre,
        precio: calcularPrecio(categoriaNombre, i),
        stockActual,
        stockMinimo,
        activo: true,
        descripcion: `${nombre}. Producto comercializado en Colombia.`,
        idCategoria,
      } as any);

      productosCreados++;
    }
  }

  console.log(
    `[SEED] Categorias creadas: ${categoriasCreadas}, existentes: ${categoriasExistentes}. ` +
      `Productos creados: ${productosCreados}, existentes: ${productosExistentes}.`
  );
}
